[workspace]
channels = ["conda-forge"]
name = "Beamline workflow"
platforms = ["linux-64", "osx-64"]

[dependencies]
python = "<3.13"
opencv = "*"
pyqt = ">=5.15.11,<6"
scikit-image = ">=0.26.0,<0.27"
ipython = ">=9.10.0,<10"
numba = "*"

[tasks]
# Start the Receiver process (runs on server with GPU for segmentation)
receiver = {cmd = "python receiver.py"}
# Run a basic test with AutoMap targetiing the remote Receiver
test = {cmd = "python producer.py -r"}

[pypi-dependencies]
tiled = { version = ">0.2.7", extras=["all"]}
bluesky-queueserver = ">=0.0.24,<0.0.25"
bluesky-queueserver-api = ">=0.0.13,<0.0.14"
hxntools = ">=0.6.5,<0.7"
cellpose = ">=4.0.8,<5"
pims = ">=0.7, <0.8"
doct = ">=1.1.0, <2"
bluesky-tiled-plugins = ">=2.0.2, <3"
#automap-hxn = { git = "https://github.com/genematx/X-AutoMap-HXN.git", branch="synaps-demo"}
automap-hxn = { path = "../X-AutoMap-HXN", editable=true}
